//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public int QUE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public bool CORRECT_ANS { get; set; }
        public int ANS_ID { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
    }
}
