//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROSTER
    {
        public int USER_ID { get; set; }
        public int COURSE_ID { get; set; }
        public int ROSTER_ID { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual USER USER { get; set; }
    }
}
